### ISSUE TITLE
Convert Database design to database objects and add sample data

### ISSUE THREAD

**Issue by lingibelli** [atthelocal/atthelocal#21]
To convert the database design to database definition statement. The attached pdf file got the database diagram showing the Table structure and relationship. The sql file made in this story would be the base line and would be used by any of us and any new comers to create database locally.

Tasks:
Create an sql file.
Add the create table statements to all of the tables.
Add Insert statement to all the tables with sample data following the dependencies.

Database Design sql File:

[atthelocal_database_SQLFile.zip](https://github.com/atthelocal/atthelocal/files/14321853/atthelocal_database_SQLFile.zip)

Database Design
[atthelocal_database_schema.pdf](https://github.com/atthelocal/atthelocal/files/14321854/atthelocal_database_schema.pdf)

**Comment by saran-mani** [comment]
`CREATE TABLE `Localite` (
  `id` integer PRIMARY KEY,
  `name` varchar(255),
  `password` varchar(255),
  `emailId` varchar(255),
  `mobilePhone` number,
  `gender` ENUM ('M', 'F', 'O'),
  `location` integer,
  `address` varchar(255),
  `emailVerified` bool,
  `phoneVerified` bool,
  `multiFactorAuth` bool,
  `numberofPagesCreated` integer,
  `numberofPagesAllowed` integer,
  `profileSettings` json
);`


- can you provide detailed use of this schema, like use of numberofpagescreated ,etc..
- user have first name,last name , join date,?

**Comment by lingibelli** [comment]
Hi @saran-mani ,
                               Thank you for raising this up. Good to have First name. Last name and JoinDate. Could you please add them?
               I have listed below the use of the fields. Mostly all are for future features. We would allow the users to create pages of their own. Like a village new board or announcement board. When we have this feature we should be able to limit the number of pages any user can create. 

      Please feel free to get back in case of any more clarifications. Thank you.


name varchar(255),
password varchar(255),
emailId varchar(255),
mobilePhone number,
gender ENUM ('M', 'F', 'O'),
location integer,
address varchar(255),
emailVerified bool,                  -> In future we have display against username if email is verified.
phoneVerified bool,                 -> In Future we can display against the username in the page if the phone is verified
multiFactorAuth bool,              -> In future if we add 2 factor authorization.  
numberofPagesCreated integer,    -> We are letting user to create pages/ groups in future. this is help us keep track. 
numberofPagesAllowed integer,     -> This is help us keep control number of pages we all the user to create.
profileSettings json                           -> This will save UI layout, their preferred home page, Dark mode, skin etc

**Comment by saran-mani** [comment]
is database should be like provided structure? or we can change?
because i change the users table like this


CREATE TABLE Users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  password VARCHAR(255),
  email VARCHAR(100) UNIQUE NOT NULL,
  mobile_number VARCHAR(15) UNIQUE NOT NULL,
  gender ENUM ('M', 'F', 'O'),
  address INT NOT NULL,
  email_verified BOOLEAN,
  mobile_number_verified BOOLEAN,
  multi_factor_auth BOOLEAN,
  numberofPagesCreated INT,
  numberofPagesAllowed INT,
  profileSettings JSON,
  FOREIGN KEY (address) REFERENCES address(address_id)
);

CREATE TABLE address (
    address_id INT PRIMARY KEY AUTO_INCREMENT,
    street VARCHAR(100),
    city_id INT,
    state_id INT,
    zip_id INT,
    FOREIGN KEY (city_id) REFERENCES cities(city_id),
    FOREIGN KEY (state_id) REFERENCES states(state_id),
    FOREIGN KEY (zip_id) REFERENCES zip_codes(zip_id)
);
CREATE TABLE cities (
    city_id INT PRIMARY KEY AUTO_INCREMENT,
    city_name VARCHAR(50)
);

CREATE TABLE states (
    state_id INT PRIMARY KEY AUTO_INCREMENT,
    state_name VARCHAR(50)
);

CREATE TABLE zip_codes (
    zip_id INT PRIMARY KEY AUTO_INCREMENT,
    zip_code VARCHAR(20)
);

**Comment by lingibelli** [comment]
@saran-mani , Hi Saran, All good. We can have it normalised like this. Also for now we can finalise a base structure to help build the UI and backend. If needed we can enhance the database structure later. Thank you Saran.

**Comment by lingibelli** [comment]
@saran-mani , Hi Saran,  Hope you doing well. For this sprint, Could you please create a SQL file with all database table create statement and another sql file with few insert statement for all the tables? The sample sql file is attached in this story.

General Idea:
First SQL file:
   1. Create Database
   2. Create all the tables, constraints

Second sql File: 
1. Insert statements for each of the tables created in the First SQL file.


  By doing this, we can populate our local database with data and start with our backend coding. thank you.

**Comment by saran-mani** [comment]
## completed the database design and ready for review and push
[atthelocaldatabase1.pdf](https://github.com/atthelocal/atthelocal/files/14666321/atthelocaldatabase1.pdf)

**Comment by lingibelli** [comment]
Hi @saran-mani ,
                              For all the tables designed, could you make the create table statement and add in this file "server/src/database/atthelocal.sql" and for all the tables, could you make few insert statement and add it in this file "server/src/database/sample_data.sql".


**STEPS:**
1. Check out branch "Marai2024-I21-AddDatabaseObjectsAndSampleData"
2. Edit "server/src/database/atthelocal.sql" and add all the Create table statements.
3. Edit "server/src/database/sample_data.sql" add insert statement with dummy data for every table.
4. Commit and push the code to repository.
5. Create a Pull request and add all of us as reviewers.


**Acceptance Criteria:**
When any developer run the "server/src/database/atthelocal.sql" file against their local database, "atthelocal" dabase should be created and all the tables should be created under that database. and when the developer runt te file "server/src/database/sample_data.sql" , then all the tables should be inserted with sample records.

**Comment by lingibelli** [comment]
@saran-mani , Thank you for the normalization. Please find my comments below.

1. Please remove the redundant name from column names. For example "gender_name" column of "Gender" table can just be "name" as it obviously refers to gender name. 
 - gender_name - name 
 - job_status - status
 - job_type - type
 - street_name - street
 - postal_code - postcode
 - 

2. listed_product_location table,  job_location table can all point to address table to avoid redundancy.
3. Job_post table can refer to "address" table instead of redundant "Job_location" table.
4. Complaint can be merged to one table.
5. Complaints table should have anonymous column do that if the user choose to be "anonymous" then we will not populate the "complained_by" column.
6. "applied_jobs" primary field can be named "id" for consistency.
7. "application_date" could be changed to "applied_date" or "applied_on"


SCENARIO:

1. When a user registers to "atthelocal"
   - Capture - first name, last name, username , password , date of birth,  email (optional) , mobile (optional), gender, location.
   - If user verified email id, then set email_verified as true.
   - If user verify mobile number by OTP, set mobile_number_verified to true
   - if user enables multi factorauthentication then set multi_factor_auth to true    
   

2. When a Logged-in user posts a job
   - Capture - Job title, Job description, company[optional] , Job location, classification, sub classification, worktype ,pay range (optional), postedby, expired by (optional) and set status to "listed/Open".
    - For any updated to the already posted job, populate the modified date. 
    
a. Any Logged in user marks any job as interested, then set a flag in the database so that we can show it to the Logged-in user all of the jobs the user is interested in the UI dashboard.
b. Any Logged in user marks any job as Not-interested, then set a flag in the database so that we can show it to the Logged-in user all of the jobs the user is Not-interested in the UI dashboard.
c. Any Logged in user marks any job as Saved, then set a flag in the database so that we can show it to the Logged-in user all of the jobs the user is Not-interested in the UI dashboard.
d. If any logged-in user complaints about any job, then set the reported flag if not anonymous. if the user chose anonymous, then do not populate this field on complain.
 

3.  When a Logged-in user posts an advertisement 
      - Capture , title, category, description, images, listed by,location, listed_date, price .
      - Set status to "listed/New/Open"
      - For for updated to the already posted advertisement, populate the modified date. 

a. Any Logged in user marks any Item as interested, then set a flag in the database so that we can show it to the Logged-in user all of the advertisement the user is interested in the UI dashboard.
b. Any Logged in user marks any Item as Not-interested, then set a flag in the database so that we can show it to the Logged-in user all of the advertisement the user is Not-interested in the UI dashboard.
c. Any Logged in user marks any Item as Saved, then set a flag in the database so that we can show it to the Logged-in user all of the advertisement the user is Not-interested in the UI dashboard.
d. If any logged-in user complaints about any Item, then set the reported flag if not anonymous. if the user chose anonymous, then do not populate this field on complain.


**General:**
Regardless of the user  logged in, if anyone visits the page, then the number of visit to that advertisement should be incremented and this should be shown to the user posted the job or advertisement.
when any logged in user , click interested, then the number of interested counter should be increased and should be shown to the user posted it. Users who not logged in cannot click interested.
Any user can complain about the advertisement or job . if the user choose to be anonymous , we should not capture the user details.

**Comment by saran-mani** [comment]
## After some changes in the database by refer the review
### Checkout the design and give the reviews for changes
https://dbdiagram.io/d/atl-review1-65fc4311ae072629ce9fb0e5

```
CREATE DATABASE atthelocal;
use atthelocal;
CREATE TABLE country(
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255)
);
CREATE TABLE address(
  id INT AUTO_INCREMENT PRIMARY KEY,
  street VARCHAR(255),
  city VARCHAR(255),
  postcode VARCHAR(15),
  country_id INT NOT NULL,
  FOREIGN KEY (country_id) REFERENCES country(id)
);
CREATE TABLE gender(
  id INT  AUTO_INCREMENT NOT NULL PRIMARY KEY,
  name VARCHAR(100)
);
CREATE TABLE users(
  id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  mobile_number VARCHAR(15) UNIQUE NOT NULL,
  gender_id INT NOT NULL,
  location_id INT NOT NULL,
  email_verified BOOLEAN DEFAULT FALSE,
  mobile_number_verified BOOLEAN DEFAULT FALSE,
  multi_factor_auth BOOLEAN DEFAULT FALSE,
  date_of_birth DATE,
  profile_settings JSON,
  FOREIGN KEY (gender_id) REFERENCES gender(id),
  FOREIGN KEY (location_id) REFERENCES address(id)
);
CREATE TABLE job_type (
  id INT AUTO_INCREMENT PRIMARY KEY,
  type VARCHAR(50) NOT NULL
);
CREATE TABLE job_status(
  id INT AUTO_INCREMENT PRIMARY KEY,
  status VARCHAR(50) NOT NULL
);
CREATE TABLE salary_range (
  id INT AUTO_INCREMENT PRIMARY KEY,
  min_salary DECIMAL(10, 2) NOT NULL,
  max_salary DECIMAL(10, 2) NOT NULL
);
CREATE TABLE job_meta_data (
  id INT AUTO_INCREMENT PRIMARY KEY,
  job_posted_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  job_modified_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  job_expire_on DATE
);
CREATE TABLE job_post (
  id INT AUTO_INCREMENT PRIMARY KEY,
  posted_by INT NOT NULL,
  job_type_id INT NOT NULL,
  title VARCHAR(100) NOT NULL,
  description VARCHAR(2000) NOT NULL,
  location_id INT NOT NULL,
  job_status_id INT NOT NULL,
  salary_range_id INT NOT NULL,
  job_meta_data_id INT NOT NULL,
  FOREIGN KEY (posted_by) REFERENCES users(id),
  FOREIGN KEY (job_type_id) REFERENCES job_type(id),
  FOREIGN KEY (job_status_id) REFERENCES job_status(id),
  FOREIGN KEY (salary_range_id) REFERENCES salary_range(id),
  FOREIGN KEY (job_meta_data_id) REFERENCES job_meta_data(id),
  FOREIGN KEY (location_id) REFERENCES address(id)
);
CREATE TABLE job_post_views (
  id INT AUTO_INCREMENT PRIMARY KEY,
  job_id INT NOT NULL,
  viewer_id INT NOT NULL,
  view_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (job_id) REFERENCES job_post(id),
  FOREIGN KEY (viewer_id) REFERENCES users(id)
);
CREATE TABLE interested_job_post (
  id INT AUTO_INCREMENT PRIMARY KEY,
  job_id INT NOT NULL,
  user_id INT NOT NULL,
  FOREIGN KEY (job_id) REFERENCES job_post(id),
  FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE TABLE not_interested_job_post (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  job_id INT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (job_id) REFERENCES job_post(id)
);
CREATE TABLE saved_job_post (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  job_id INT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (job_id) REFERENCES job_post(id)
);
CREATE TABLE applied_jobs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  job_id INT NOT NULL,
  applied_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (job_id) REFERENCES job_post(id)
);
CREATE TABLE shortlisted_jobs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  job_id INT NOT NULL,
  shortlist_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (job_id) REFERENCES job_post(id)
);
CREATE TABLE product_categories (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL
);
CREATE TABLE listed_product(
  id INT AUTO_INCREMENT PRIMARY KEY,
  listed_by INT NOT NULL,
  title VARCHAR(100) NOT NULL,
  description TEXT,
  price DECIMAL(10, 2) NOT NULL,
  category_id INT NOT NULL,
  location_id INT NOT NULL,
  stock_quantity VARCHAR(100),
  FOREIGN KEY (listed_by) REFERENCES users(id),
  FOREIGN KEY (category_id) REFERENCES product_categories(id),
  FOREIGN KEY (location_id) REFERENCES address(id)
);
CREATE TABLE complaints (
  id INT AUTO_INCREMENT PRIMARY KEY,
  complaint_about VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  complained_by INT,
  anonymous BOOLEAN NOT NULL DEFAULT FALSE,
  job_post_id INT,
  product_id INT,
  FOREIGN KEY (complained_by) REFERENCES users(id),
  FOREIGN KEY (job_post_id) REFERENCES job_post(id),
  FOREIGN KEY (product_id) REFERENCES listed_product(id)
);
CREATE TABLE interested_products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  product_id INT NOT NULL,
  user_id INT NOT NULL,
  FOREIGN KEY (product_id) REFERENCES listed_product(id),
  FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE TABLE not_interested_products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  product_id INT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (product_id) REFERENCES listed_product(id)
);
CREATE TABLE saved_products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  product_id INT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (product_id) REFERENCES listed_product(id)
);
```

**Comment by saran-mani** [comment]
## The Database Design  intrested,not intrested and saved  tables combine in one table.

```
DROP DATABASE atthelocal;
CREATE DATABASE atthelocal;
use atthelocal;
CREATE TABLE country(
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255)
);
CREATE TABLE address(
  id INT AUTO_INCREMENT PRIMARY KEY,
  street VARCHAR(255),
  city VARCHAR(255),
  postcode VARCHAR(15),
  country_id INT NOT NULL,
  FOREIGN KEY (country_id) REFERENCES country(id)
);
CREATE TABLE gender(
  id INT  AUTO_INCREMENT NOT NULL PRIMARY KEY,
  name VARCHAR(100)
);
CREATE TABLE users(
  id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  mobile_number VARCHAR(15) UNIQUE NOT NULL,
  gender_id INT NOT NULL,
  location_id INT NOT NULL,
  email_verified BOOLEAN DEFAULT FALSE,
  mobile_number_verified BOOLEAN DEFAULT FALSE,
  multi_factor_auth BOOLEAN DEFAULT FALSE,
  date_of_birth DATE,
  profile_settings JSON,
  FOREIGN KEY (gender_id) REFERENCES gender(id),
  FOREIGN KEY (location_id) REFERENCES address(id)
);
CREATE TABLE job_type (
  id INT AUTO_INCREMENT PRIMARY KEY,
  type VARCHAR(50) NOT NULL
);
CREATE TABLE job_status(
  id INT AUTO_INCREMENT PRIMARY KEY,
  status VARCHAR(50) NOT NULL
);
CREATE TABLE salary_range (
  id INT AUTO_INCREMENT PRIMARY KEY,
  min_salary DECIMAL(10, 2) NOT NULL,
  max_salary DECIMAL(10, 2) NOT NULL
);
CREATE TABLE job_meta_data (
  id INT AUTO_INCREMENT PRIMARY KEY,
  job_posted_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  job_modified_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  job_expire_on DATE
);
CREATE TABLE job_post (
  id INT AUTO_INCREMENT PRIMARY KEY,
  posted_by INT NOT NULL,
  job_type_id INT NOT NULL,
  title VARCHAR(100) NOT NULL,
  description VARCHAR(2000) NOT NULL,
  location_id INT NOT NULL,
  job_status_id INT NOT NULL,
  salary_range_id INT NOT NULL,
  job_meta_data_id INT NOT NULL,
  FOREIGN KEY (posted_by) REFERENCES users(id),
  FOREIGN KEY (job_type_id) REFERENCES job_type(id),
  FOREIGN KEY (job_status_id) REFERENCES job_status(id),
  FOREIGN KEY (salary_range_id) REFERENCES salary_range(id),
  FOREIGN KEY (job_meta_data_id) REFERENCES job_meta_data(id),
  FOREIGN KEY (location_id) REFERENCES address(id)
);
CREATE TABLE job_post_views (
  id INT AUTO_INCREMENT PRIMARY KEY,
  job_id INT NOT NULL,
  viewer_id INT NOT NULL,
  view_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (job_id) REFERENCES job_post(id),
  FOREIGN KEY (viewer_id) REFERENCES users(id)
);

CREATE TABLE applied_jobs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  job_id INT NOT NULL,
  applied_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (job_id) REFERENCES job_post(id)
);
CREATE TABLE shortlisted_jobs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  job_id INT NOT NULL,
  shortlist_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (job_id) REFERENCES job_post(id)
);
CREATE TABLE product_categories (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL
);
CREATE TABLE listed_product(
  id INT AUTO_INCREMENT PRIMARY KEY,
  listed_by INT NOT NULL,
  title VARCHAR(100) NOT NULL,
  description TEXT,
  price DECIMAL(10, 2) NOT NULL,
  category_id INT NOT NULL,
  location_id INT NOT NULL,
  stock_quantity VARCHAR(100),
  FOREIGN KEY (listed_by) REFERENCES users(id),
  FOREIGN KEY (category_id) REFERENCES product_categories(id),
  FOREIGN KEY (location_id) REFERENCES address(id)
);
CREATE TABLE complaints (
  id INT AUTO_INCREMENT PRIMARY KEY,
  complaint_about VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  complained_by INT,
  anonymous BOOLEAN NOT NULL DEFAULT FALSE,
  job_post_id INT,
  product_id INT,
  FOREIGN KEY (complained_by) REFERENCES users(id),
  FOREIGN KEY (job_post_id) REFERENCES job_post(id),
  FOREIGN KEY (product_id) REFERENCES listed_product(id)
);

CREATE TABLE product_images (
  id INT AUTO_INCREMENT PRIMARY KEY,
  product_id INT NOT NULL,
  image_url VARCHAR(255) NOT NULL,
  uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (product_id) REFERENCES listed_product(id)
);
CREATE TABLE product_image_relations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  product_id INT NOT NULL,
  image_id INT NOT NULL,
  FOREIGN KEY (product_id) REFERENCES listed_product(id),
  FOREIGN KEY (image_id) REFERENCES product_images(id)
);

CREATE TABLE user_actions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  action_type ENUM('interest', 'not_interest', 'save') NOT NULL,
  job_id INT,
  product_id INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (job_id) REFERENCES job_post(id),
  FOREIGN KEY (product_id) REFERENCES listed_product(id)
);

```
---------------------------------------------------------------------------------------
## Dummy data for the DB

```
-- Dummy data for country table
INSERT INTO country (name) VALUES
('India'),
('United States'),
('United Kingdom'),
('Australia'),
('Canada');

-- Dummy data for address table
INSERT INTO address (street, city, postcode, country_id) VALUES
('123 Main Street', 'Mumbai', '400001', 1),
('456 Oak Avenue', 'New York', '10001', 2),
('789 High Street', 'London', 'SW1A 1AA', 3),
('1010 Bay Street', 'Sydney', '2000', 4),
('111 Maple Drive', 'Toronto', 'M5H 2N2', 5);

-- Dummy data for gender table
INSERT INTO gender (name) VALUES
('Male'),
('Female'),
('Other');

-- Dummy data for users table
INSERT INTO users (first_name, last_name, password, email, mobile_number, gender_id, location_id, date_of_birth) VALUES
('Ramesh', 'Kumar', 'password123', 'ramesh@example.com', '9876543210', 1, 1, '1990-05-15'),
('Priya', 'Patel', 'pass123', 'priya@example.com', '9876543211', 2, 2, '1988-09-25'),
('Amit', 'Sharma', 'securepass', 'amit@example.com', '9876543212', 1, 3, '1995-03-10'),
('Neha', 'Verma', 'mypassword', 'neha@example.com', '9876543213', 2, 4, '1992-11-20'),
('Suresh', 'Singh', 'password1234', 'suresh@example.com', '9876543214', 1, 5, '1985-07-08');

-- Dummy data for job_type table
INSERT INTO job_type (type) VALUES
('Full-time'),
('Part-time'),
('Contract'),
('Freelance'),
('Internship');

-- Dummy data for job_status table
INSERT INTO job_status (status) VALUES
('Active'),
('Inactive'),
('Closed'),
('Pending'),
('Filled');

-- Dummy data for salary_range table
INSERT INTO salary_range (min_salary, max_salary) VALUES
(30000, 50000),
(60000, 80000),
(40000, 60000),
(70000, 90000),
(50000, 70000);

-- Dummy data for job_meta_data table
INSERT INTO job_meta_data (job_posted_on, job_modified_on, job_expire_on) VALUES
('2024-03-01 09:00:00', '2024-03-05 12:00:00', '2024-04-30'),
('2024-03-02 10:00:00', '2024-03-06 11:00:00', '2024-05-15'),
('2024-03-03 11:00:00', '2024-03-07 10:00:00', '2024-06-30'),
('2024-03-04 12:00:00', '2024-03-08 09:00:00', '2024-07-15'),
('2024-03-05 13:00:00', '2024-03-09 08:00:00', '2024-08-31');

-- Dummy data for job_post table
INSERT INTO job_post (posted_by, job_type_id, title, description, location_id, job_status_id, salary_range_id, job_meta_data_id) VALUES
(1, 1, 'Software Engineer', 'We are looking for a skilled software engineer to join our team.', 1, 1, 1, 1),
(2, 2, 'Marketing Specialist', 'We need a marketing specialist to help promote our products.', 2, 1, 2, 2),
(3, 3, 'Project Manager', 'Experienced project manager needed to oversee multiple projects.', 3, 1, 3, 3),
(4, 4, 'Graphic Designer', 'Talented graphic designer required to create stunning visuals.', 4, 1, 4, 4),
(5, 5, 'Data Analyst Intern', 'Seeking a data analyst intern for a summer internship.', 5, 1, 5, 5);

-- Dummy data for job_post_views table
INSERT INTO job_post_views (job_id, viewer_id, view_time) VALUES
(1, 2, '2024-03-01 10:00:00'),
(1, 3, '2024-03-01 11:00:00'),
(2, 4, '2024-03-02 10:00:00'),
(3, 5, '2024-03-03 09:00:00'),
(4, 1, '2024-03-04 08:00:00');

-- Dummy data for applied_jobs table
INSERT INTO applied_jobs (user_id, job_id) VALUES
(1, 1),
(2, 2),
(3, 3),
(4, 4),
(5, 5);

-- Dummy data for shortlisted_jobs table
INSERT INTO shortlisted_jobs (user_id, job_id) VALUES
(1, 2),
(2, 3),
(3, 4),
(4, 5),
(5, 1);

-- Dummy data for product_categories table
INSERT INTO product_categories (name) VALUES
('Electronics'),
('Clothing'),
('Books'),
('Home & Garden'),
('Toys');

-- Dummy data for listed_product table
INSERT INTO listed_product (listed_by, title, description, price, category_id, location_id, stock_quantity) VALUES
(1, 'Smartphone', 'Latest smartphone with advanced features.', 500.00, 1, 1, '10'),
(2, 'T-shirt', 'Comfortable cotton T-shirt in assorted colors.', 20.00, 2, 2, '50'),
(3, 'Java Programming Book', 'Comprehensive guide to Java programming language.', 30.00, 3, 3, '20'),
(4, 'Garden Hose', 'Durable garden hose for watering plants.', 15.00, 4, 4, '30'),
(5, 'LEGO Set', 'Build and play with this fun LEGO set.', 50.00, 5, 5, '15');

-- Dummy data for complaints table
INSERT INTO complaints (complaint_about, description, complained_by, anonymous, job_post_id, product_id) VALUES
('Product', 'Received damaged product.', 1, 0, NULL, 5),
('Job Post', 'Misleading job description.', 2, 1, 1, NULL),
('Product', 'Product did not match description.', 3, 0, NULL, 2),
('Job Post', 'No response after applying for the job.', 4, 0, 2, NULL),
('Product', 'Received wrong size.', 5, 0, NULL, 1);

-- Dummy data for user_actions table
INSERT INTO user_actions (user_id, action_type, job_id, product_id) VALUES
(1, 'interest', 1, NULL),
(2, 'not_interest', NULL, 2),
(3, 'save', 3, NULL),
(4, 'interest', 4, NULL),
(5, 'save', NULL, 5);

-- Dummy data for product_images table
INSERT INTO product_images (product_id, image_url) VALUES
(1, 'https://example.com/image1.jpg'),
(1, 'https://example.com/image2.jpg'),
(2, 'https://example.com/image3.jpg'),
(3, 'https://example.com/image4.jpg'),
(4, 'https://example.com/image5.jpg');

-- Dummy data for product_image_relations table
INSERT INTO product_image_relations (product_id, image_id) VALUES
(1, 1),
(1, 2),
(2, 3),
(3, 4),
(4, 5);

```

**Comment by lingibelli** [comment]
Code merged to Master.

https://github.com/atthelocal/atthelocal/commit/64d0c9393c99a8350f99a67672347ea0d5269eb8

**Comment by lingibelli** [comment]
Initial sql file created.

**Comment by lingibelli** [comment]
@buvi05 , Hi Bhuvana, The database design and the sample data are in this story.
